#!/usr/bin/env bash
#
# Print the socials - indended to be passed to `tools/box`
#



. ./theme || exit

readarray -t SOCIALS << "EOF"
Instagram|https://kryptikk.de/instagram
YouTube|https://kryptikk.de/youtube
Patreon|https://kryptikk.de/patreon
Discord|https://kryptikk.de/discord
Twitch|https://kryptikk.de/twitch
EOF

UNDERLINE=$'\x1b[3m'

for line in "${SOCIALS[@]}"; do
	IFS='|' read -r name url <<< "$line"

	echo -n "$COLOR2$name$RST"
	echo -n '|'
	echo -n "$UNDERLINE$COLOR2$url$RST"
	echo
done
