#!/usr/bin/env bash
#
# Convert the list of events into JSON format - pass an argument to make it
# JSONP instead.
#


varname=$1

baselink='https://kryptikk.de'

printf -v now '%(%s)T' -1
output=$(jq \
	--argjson date "$now" \
	--arg link "$baselink" \
	'{
		"name": "Lars Junker Calltermine",
		"site": $link,
		"generated": $date,
		"drei": [
			.[] | {
				number: .nummer,
				name: .titel,
				collected: (if .collected then "gesammelt" else "nicht gesammelt" end),
				cover: .cover
			}
		]
	}' drei-fragezeichen.json
)

# print the data (optionally as jsonp if the first arg is set)
if [[ -n $varname ]]; then
	output="const $varname = $output;"
fi
echo "$output"
